name: 'Automated Tag Creator '
description: 'Track version changes in local files for automatic tag creation'
author: 'smartforce-io'

inputs:
  type:
    description: 'File to track version of the app'
    required: true
  secrets:
    description: 'Token to access repository'
    required: true
  commit:
    description: 'Commit that triggered the action.'
    default: ${{github.sha}}
    required: false
  behavior:
    description: 'ATC can create tag for current commit.
    Use after for this, or previous commit, use before for this.
    The default behavior is after'
    required: false
    default: after
  template:
    description: 'The default template is "v{{.Version}}'
    required: false
    default: v{{.Version}}
  repository:
    description: 'Repository for tag creation'
    required: false
    default: ${{ github.repository }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    FILE_TYPE: ${{ inputs.type }}
    COMMIT_SHA: ${{ inputs.commit }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    BEHAVIOR: ${{ inputs.behavior }}
    TEMPLATE: ${{ inputs.template }}

