steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker build -t gcr.io/atc-sf/atc-backend:latest -f Dockerfile --build-arg GH_PEM_DATA="$$GH_PEM" .'
    secretEnv: ['GH_PEM']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/atc-sf/atc-backend:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'atc-backend'
      - '--image'
      - 'gcr.io/atc-sf/atc-backend:latest'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'

secrets:
  - kmsKeyName: 'projects/project-id/locations/global/keyRings/keyring-name/cryptoKeys/key-name'
    secretEnv:
      GH_PEM: CiQALk5bqHt------E7rLYCKVhM=

images:
  - 'gcr.io/atc-sf/atc-backend:latest'